apiVersion: v1
kind: Pod
metadata:
  name: limit-test
spec:
  containers:
  -  name: cpu-mem
     image: saiyam911/stress
     resources:
       limits:
         cpu: "1"
         memory: "200Mi"
       requests:
         cpu: "500m"
         memory: "100Mi"
     command: ["stress"]
     args: ["--cpu", "2"] 
     #args: ["--vm","1","--vm-bytes", "250M", "--vm-hang", "1"] 